applications:
  - entry: src/index
    exposes: []
    name: home
    output: dist
    remotes: []
  - entry: src/index
    exposes: []
    name: user
    output: dist
    remotes: []
  - entry: src/index
    exposes: []
    name: setting
    output: dist
    remotes: []
packages: packages
protocol: http
url: localhost
