applications:
  - entry: src/index
    exposes: []
    name: home
    output: dist
    remotes: []
  - entry: src/index
    exposes: []
    name: user
    output: dist
    remotes: []
  - name: setting
packages: packages
protocol: http
url: localhost
